name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: nicomedrano/homyscrapy:v0.3
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          python homyscrapy/inmotico-scrapy.py