name: Build
on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        default: prod
jobs:
  build_prod:
    runs-on: nicomedrano/homyscrapy:latest
    if: ${{ github.event_name != 'schedule' && github.event_name != 'pull_request'}}
    env:
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Build
        run: |
          python homyscrapy/inmotico-scrapy.py