name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: nicomedrano/homyscrapy:v0.1
    env:
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Build
        run: |
          python homyscrapy/inmotico-scrapy.py